DELETE FROM USER_ROLE;
DELETE FROM ROLE_PERMISSION;
DELETE FROM USER;
DELETE FROM ROLE;
DELETE FROM PERMISSION;

INSERT INTO PERMISSION VALUES(1,'TEST_PERMISSION');
INSERT INTO ROLE VALUES(1, 'TEST_ROLE');
INSERT INTO ROLE_PERMISSION(ROLE_ID,PERMISSION_ID) VALUES(1,1);
INSERT INTO USER(ID,USERNAME,PASSWORD) VALUES(1,'testuser','5554432');
INSERT INTO USER_ROLE(USER_ID,ROLE_ID) VALUES(1,1);