DELETE FROM USER_ROLE;
DELETE FROM ROLE_PERMISSION;
DELETE FROM USER;
DELETE FROM ROLE;
DELETE FROM PERMISSION;

DELETE FROM USER_DATA;

INSERT INTO PERMISSION VALUES(1,'TEST_PERMISSION');
INSERT INTO PERMISSION VALUES(2,'WORKER_PERMISSION');
INSERT INTO ROLE VALUES(1, 'TEST_ROLE');
INSERT INTO ROLE VALUES(2, 'WORKER_ROLE');
INSERT INTO ROLE_PERMISSION(ROLE_ID,PERMISSION_ID) VALUES(1,1);
INSERT INTO ROLE_PERMISSION(ROLE_ID,PERMISSION_ID) VALUES(2,2);
INSERT INTO USER(ID,USERNAME,PASSWORD) VALUES(1,'jankowalski','5554432');
INSERT INTO USER(ID,USERNAME,PASSWORD) VALUES(2,'adamnowak','5554432');
INSERT INTO USER_DATA(ID, SECURITY_ID, NAME, SURNAME, EMAIL, ACTIVE) VALUES(1, 1, 'Jan', 'Kowalski', 'jankowalski@wp.pl', true);
INSERT INTO USER_DATA(ID, SECURITY_ID, NAME, SURNAME, EMAIL, ACTIVE) VALUES(2, 2, 'Adam', 'Nowak', 'adamnowak@wp.pl', true);
INSERT INTO WORKER(ID, USER_ID, DRIVER_LICENSE_NUMBER, IDNUMBER, PESEL) VALUES(1,2,'21/21/12345','DKF291829','97041812122');