DELETE FROM BUS_STOP;
DELETE FROM SCHEDULE;
DELETE FROM TOWN;

INSERT INTO TOWN VALUES(1, 'WARSZAWA');
INSERT INTO TOWN VALUES(2, 'KIELCE');
INSERT INTO TOWN VALUES(3, 'BIALYSTOK');
INSERT INTO TOWN VALUES(4, 'SANDOMIERZ');