DELETE FROM BUS_STOP;
DELETE FROM SCHEDULE;
DELETE FROM TOWN;

INSERT INTO TOWN VALUES(1, 'WARSZAWA');
INSERT INTO TOWN VALUES(2, 'KIELCE');
INSERT INTO TOWN VALUES(3, 'BIALYSTOK');
INSERT INTO TOWN VALUES(4, 'SANDOMIERZ');

INSERT INTO SCHEDULE VALUES(1, 1, 1, true, 15);
INSERT INTO BUS_STOP(ID, SCHEDULE_ID, TOWN_ID, ARRIVAL_DATE, DEPARTURE_DATE) VALUES(1, 1, 1, parsedatetime('18-04-2020 09:00:00', 'dd-MM-yyyy hh:mm:ss'), parsedatetime('18-04-2020 09:05:00', 'dd-MM-yyyy hh:mm:ss'));
